# Generated by Django 4.2.7 on 2023-11-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_unit_purchase_quantity_purchase_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='tags',
            field=models.ManyToManyField(to='main.tag'),
        ),
    ]
